apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask-deployment
        image: acraksndma3t6oaphlc.azurecr.io/flask:26
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2000
        resources:
          requests:
            cpu: 80m
            memory: 64Mi
          limits:
            cpu: 180m
            memory: 128Mi       
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: flask
  ports:
  - port: 2000
    targetPort: 2000
